
name: ci-sub001
run-name: ${{ github.actor }} pushed sub001
on:
  push:
    paths:
      - 'sub001/**'

jobs:
  check-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile check
        run: gcc main.c -o main
        working-directory: ./sub001

