
name: ci-sub002
run-name: ${{ github.actor }} pushed sub002
on:
  push:
    paths:
      - 'sub002/**'

jobs:
  check-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile check
        run: make
        working-directory: ./sub002

