
name: learn-job-step-shell-script
run-name: ${{ github.actor }} is learning (job-step-shell-script)
on: [push]
jobs:
  check-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: bash ./scripts/script01.sh

