
# see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
#   Minute [0,59]
#   Hour [0,23]
#   Day of the month [1,31]
#   Month of the year [1,12]
#   Day of the week ([0,6] with 0=Sunday)


name: simple-schedule
run-name: Scheduled
on:
  schedule:
    # min hour day month year week
    - cron: '32 * * * *'

jobs:
  scheduled-ci:
    runs-on: ubuntu-latest
    steps:
      - run: |
          date
          echo "Run on schedule"

